name: Publish
on:
    release:
        types: [published]

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2
            - name: 🟢 node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: 📦 install
              run: NOYARNPREINSTALL=1 yarn install
            - name: 📦 build
              run: NOYARNPREINSTALL=1 yarn build:ci
            - name: 🚀 publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
